# -*- coding: utf-8 -*-
"""Paper_Rock .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0UqlnfDJFQbJcRqHa3GKmMaTb_zCoy0
"""

import random

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "scissors" and computer_choice == "paper") or \
         (user_choice == "paper" and computer_choice == "rock"):
        return "You win!"
    else:
        return "You lose!"

def main():
    user_score = 0
    computer_score = 0

    while True:
        print("Welcome to Rock-Paper-Scissors Game!")
        print("Choose: rock, paper, or scissors. To exit, type 'exit'.")

        user_choice = input("Your choice: ").lower()

        if user_choice == "exit":
            break

        choices = ["rock", "paper", "scissors"]
        computer_choice = random.choice(choices)

        if user_choice in choices:
            result = determine_winner(user_choice, computer_choice)
            print(f"You chose {user_choice}, computer chose {computer_choice}.")
            print(result)

            if result == "You win!":
                user_score += 1
            elif result == "You lose!":
                computer_score += 1

            print(f"Your score: {user_score}, Computer's score: {computer_score}\n")
        else:
            print("Invalid choice. Please choose again.")

if __name__ == "__main__":
    main()